### ISSUE TITLE
ERROR: Could not open the input file (Invalid data found when processing input)

### ISSUE THREAD

**Issue by kzmaker** [unmade/audiomatch#16] opened 2022-07-27 05:29 UTC
ERROR: Could not open the input file (Invalid data found when processing input)

**Comment by unmade** [comment] 2022-07-27 13:36
Please provide more information, what audio file format is it?

**Comment by unmade** [comment] 2023-01-09 20:31
I'm gonna close it as no additional information were provided and most likely the problem is that audio file is not supported by the `chromaprint` itself.

**Closed by unmade** 2023-01-09 20:31 UTC
